### ISSUE TITLE
Use default server.properties settings

### ISSUE THREAD

**Issue by gquintana** [gprivitera/kafka-docker#3]
The default server.properties provided by Kafka contains sensible defaults.

IMHO using the file provided by the Kafka team and then replacing (using sed or the like) settings with provided environment vars is better than creating a new server.properties from scratch and forgetting important defaults.

**Comment by gprivitera** [comment]
Am I wrong or options missing from the config file are set at default values? 
If so what you are asking here de facto doesn't change anything.
